<?php

namespace Database\Seeders;

use App\Models\State;
use Illuminate\Database\Seeder;

class StateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $states = [
//China State Starts here
            [
                'id' => 1,
                'country_id' => 1,
                'state_name' => 'Zhejiang',
                'state_code' => 'ZJ',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'country_id' => 1,
                'state_name' => 'Fujian',
                'state_code' => 'FJ',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'country_id' => 1,
                'state_name' => 'Shanghai',
                'state_code' => 'SH',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'country_id' => 1,
                'state_name' => 'Jiangsu',
                'state_code' => 'JS',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'country_id' => 1,
                'state_name' => 'Anhui',
                'state_code' => 'AH',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'country_id' => 1,
                'state_name' => 'Shandong',
                'state_code' => 'SD',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'country_id' => 1,
                'state_name' => 'Jilin',
                'state_code' => 'JL',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'country_id' => 1,
                'state_name' => 'Shanxi',
                'state_code' => 'SX',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'country_id' => 1,
                'state_name' => 'Taiwan Province, People\'s Republic of China',
                'state_code' => 'TW',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'country_id' => 1,
                'state_name' => 'Jiangxi',
                'state_code' => 'JX',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'country_id' => 1,
                'state_name' => 'Beijing',
                'state_code' => 'BJ',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'country_id' => 1,
                'state_name' => 'Hunan',
                'state_code' => 'HN',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'country_id' => 1,
                'state_name' => 'Henan',
                'state_code' => 'HA',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'country_id' => 1,
                'state_name' => 'Yunnan',
                'state_code' => 'YN',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'country_id' => 1,
                'state_name' => 'Guizhou',
                'state_code' => 'GZ',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'country_id' => 1,
                'state_name' => 'Ningxia Hui Autonomous Region',
                'state_code' => 'NX',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'country_id' => 1,
                'state_name' => 'Xinjiang',
                'state_code' => 'XJ',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],

            [
                'id' => 18,
                'country_id' => 1,
                'state_name' => 'Tibet Autonomous Region',
                'state_code' => 'XZ',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],

            [
                'id' => 19,
                'country_id' => 1,
                'state_name' => 'Heilongjiang',
                'state_code' => 'HL',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],

            [
                'id' => 20,
                'country_id' => 1,
                'state_name' => 'Macau',
                'state_code' => 'MO',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],

            [
                'id' => 21,
                'country_id' => 1,
                'state_name' => 'Hong Kong',
                'state_code' => 'HK',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],

            [
                'id' => 22,
                'country_id' => 1,
                'state_name' => 'Liaoning',
                'state_code' => 'LN',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],

            [
                'id' => 23,
                'country_id' => 1,
                'state_name' => 'Inner Mongolia',
                'state_code' => 'NM',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],

            [
                'id' => 24,
                'country_id' => 1,
                'state_name' => 'Qinghai',
                'state_code' => 'QH',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],

            [
                'id' => 25,
                'country_id' => 1,
                'state_name' => 'Chongqing',
                'state_code' => 'CQ',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],

            [
                'id' => 26,
                'country_id' => 1,
                'state_name' => 'Shaanxi',
                'state_code' => 'SN',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],

            [
                'id' => 28,
                'country_id' => 1,
                'state_name' => 'Hainan',
                'state_code' => 'HI',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],

            [
                'id' => 29,
                'country_id' => 1,
                'state_name' => 'Hubei',
                'state_code' => 'HB',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],

            [
                'id' => 30,
                'country_id' => 1,
                'state_name' => 'Gansu',
                'state_code' => 'GS',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],

            [
                'id' => 31,
                'country_id' => 1,
                'state_name' => 'Keelung',
                'state_code' => 'TW-KEE',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],

            [
                'id' => 32,
                'country_id' => 1,
                'state_name' => 'Sichuan',
                'state_code' => 'SC',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],

            [
                'id' => 33,
                'country_id' => 1,
                'state_name' => 'Guangxi Zhuang Autonomous Region',
                'state_code' => 'GX',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],

            [
                'id' => 34,
                'country_id' => 1,
                'state_name' => 'Guangdong',
                'state_code' => 'GD',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],

            [
                'id' => 35,
                'country_id' => 1,
                'state_name' => 'Hebei',
                'state_code' => 'HE',
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
//China States Ends here

//Cambodia States Starts here


            [
                'id' => 36,
                'country_id' => 2,
                'state_name' => 'Svay Rieng Province',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 37,
                'country_id' => 2,
                'state_name' => 'Preah Vihear Province',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 38,
                'country_id' => 2,
                'state_name' => 'Prey Veng Province',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 39,
                'country_id' => 2,
                'state_name' => 'Takéo Province',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 40,
                'country_id' => 2,
                'state_name' => 'Battambang Province',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 41,
                'country_id' => 2,
                'state_name' => 'Pursat Province',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 42,
                'country_id' => 2,
                'state_name' => 'Kep Province',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 43,
                'country_id' => 2,
                'state_name' => 'Kampong Chhnang Province',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 44,
                'country_id' => 2,
                'state_name' => 'Pailin Province',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 45,
                'country_id' => 2,
                'state_name' => 'Kampot Province',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 46,
                'country_id' => 2,
                'state_name' => 'Koh Kong Province',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 47,
                'country_id' => 2,
                'state_name' => 'Kandal Province',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 48,
                'country_id' => 2,
                'state_name' => 'Banteay Meanchey Province',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 49,
                'country_id' => 2,
                'state_name' => 'Mondulkiri Province',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 50,
                'country_id' => 2,
                'state_name' => 'Kratié Province',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 51,
                'country_id' => 2,
                'state_name' => 'Oddar Meanchey Province',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 52,
                'country_id' => 2,
                'state_name' => 'Kampong Speu Province',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 53,
                'country_id' => 2,
                'state_name' => 'Sihanoukville Province',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 54,
                'country_id' => 2,
                'state_name' => 'Ratanakiri Province',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 55,
                'country_id' => 2,
                'state_name' => 'Kampong Cham Province',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 56,
                'country_id' => 2,
                'state_name' => 'Siem Reap Province',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 57,
                'country_id' => 2,
                'state_name' => 'Stung Treng Province',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 58,
                'country_id' => 2,
                'state_name' => 'Phnom Penh',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],

//Cambodia States Ends here

//Vietnam States Starts here

            [
                'id' => '59',
                'country_id' => 3,
                'state_name' => 'Hưng Yên',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '60',
                'country_id' => 3,
                'state_name' => 'Đồng Tháp',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '61',
                'country_id' => 3,
                'state_name' => 'Bà Rịa-Vũng Tàu',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '62',
                'country_id' => 3,
                'state_name' => 'Thanh Hóa',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '63',
                'country_id' => 3,
                'state_name' => 'Kon Tum',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '64',
                'country_id' => 3,
                'state_name' => 'Điện Biên',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '65',
                'country_id' => 3,
                'state_name' => 'Vĩnh Phúc',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '66',
                'country_id' => 3,
                'state_name' => 'Thái Bình',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '67',
                'country_id' => 3,
                'state_name' => 'Quảng Nam',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '68',
                'country_id' => 3,
                'state_name' => 'Hậu Giang',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '69',
                'country_id' => 3,
                'state_name' => 'Cà Mau',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '70',
                'country_id' => 3,
                'state_name' => 'Hà Giang',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '71',
                'country_id' => 3,
                'state_name' => 'Nghệ An',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '72',
                'country_id' => 3,
                'state_name' => 'Tiền Giang',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '73',
                'country_id' => 3,
                'state_name' => 'Cao Bằng',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '74',
                'country_id' => 3,
                'state_name' => 'Haiphong',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '75',
                'country_id' => 3,
                'state_name' => 'Yên Bái',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '76',
                'country_id' => 3,
                'state_name' => 'Bình Dương',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '77',
                'country_id' => 3,
                'state_name' => 'Ninh Bình',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '78',
                'country_id' => 3,
                'state_name' => 'Bình Thuận',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '79',
                'country_id' => 3,
                'state_name' => 'Ninh Thuận',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '80',
                'country_id' => 3,
                'state_name' => 'Nam Định',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '81',
                'country_id' => 3,
                'state_name' => 'Vĩnh Long',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '82',
                'country_id' => 3,
                'state_name' => 'Bắc Ninh',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '83',
                'country_id' => 3,
                'state_name' => 'Lạng Sơn',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '84',
                'country_id' => 3,
                'state_name' => 'Khánh Hòa',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '85',
                'country_id' => 3,
                'state_name' => 'An Giang',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '86',
                'country_id' => 3,
                'state_name' => 'Tuyên Quang',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '87',
                'country_id' => 3,
                'state_name' => 'Bến Tre',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '88',
                'country_id' => 3,
                'state_name' => 'Bình Phước',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '89',
                'country_id' => 3,
                'state_name' => 'Thừa Thiên-Huế',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '90',
                'country_id' => 3,
                'state_name' => 'Hòa Bình',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '91',
                'country_id' => 3,
                'state_name' => 'Kiên Giang',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '92',
                'country_id' => 3,
                'state_name' => 'Phú Thọ',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '93',
                'country_id' => 3,
                'state_name' => 'Hà Nam',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '94',
                'country_id' => 3,
                'state_name' => 'Quảng Trị',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '95',
                'country_id' => 3,
                'state_name' => 'Bạc Liêu',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '96',
                'country_id' => 3,
                'state_name' => 'Trà Vinh',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '97',
                'country_id' => 3,
                'state_name' => 'Da Nang',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '98',
                'country_id' => 3,
                'state_name' => 'Thái Nguyên',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '99',
                'country_id' => 3,
                'state_name' => 'Long An',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '100',
                'country_id' => 3,
                'state_name' => 'Quảng Bình',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '101',
                'country_id' => 3,
                'state_name' => 'Hanoi',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '102',
                'country_id' => 3,
                'state_name' => 'Ho Chi Minh City',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '103',
                'country_id' => 3,
                'state_name' => 'Sơn La',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '104',
                'country_id' => 3,
                'state_name' => 'Gia Lai',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '105',
                'country_id' => 3,
                'state_name' => 'Quảng Ninh',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '106',
                'country_id' => 3,
                'state_name' => 'Bắc Giang',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '107',
                'country_id' => 3,
                'state_name' => 'Hà Tĩnh',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '108',
                'country_id' => 3,
                'state_name' => 'Lào Cai',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '109',
                'country_id' => 3,
                'state_name' => 'Lâm Đồng',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '110',
                'country_id' => 3,
                'state_name' => 'Sóc Trăng',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '111',
                'country_id' => 3,
                'state_name' => 'Hà Tây',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '112',
                'country_id' => 3,
                'state_name' => 'Đồng Nai',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '113',
                'country_id' => 3,
                'state_name' => 'Bắc Kạn',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '114',
                'country_id' => 3,
                'state_name' => 'Đắk Nông',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '115',
                'country_id' => 3,
                'state_name' => 'Phú Yên',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '116',
                'country_id' => 3,
                'state_name' => 'Lai Châu',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '117',
                'country_id' => 3,
                'state_name' => 'Tây Ninh',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '118',
                'country_id' => 3,
                'state_name' => 'Hải Dương',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '119',
                'country_id' => 3,
                'state_name' => 'Quảng Ngãi',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '120',
                'country_id' => 3,
                'state_name' => 'Đắk Lắk',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '121',
                'country_id' => 3,
                'state_name' => 'Bình Định',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],

//Vietnam States Ends here
//Thailand States Starts here

            [
                'id' => '122',
                'country_id' => 4,
                'state_name' => 'Krabi',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '123',
                'country_id' => 4,
                'state_name' => 'Ranong',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '124',
                'country_id' => 4,
                'state_name' => 'Nong Bua Lam Phu',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '125',
                'country_id' => 4,
                'state_name' => 'Samut Prakan',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '126',
                'country_id' => 4,
                'state_name' => 'Surat Thani',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '127',
                'country_id' => 4,
                'state_name' => 'Lamphun',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '128',
                'country_id' => 4,
                'state_name' => 'Nong Khai',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '129',
                'country_id' => 4,
                'state_name' => 'Khon Kaen',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '130',
                'country_id' => 4,
                'state_name' => 'Chanthaburi',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '131',
                'country_id' => 4,
                'state_name' => 'Saraburi',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '132',
                'country_id' => 4,
                'state_name' => 'Phatthalung',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '133',
                'country_id' => 4,
                'state_name' => 'Uttaradit',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '134',
                'country_id' => 4,
                'state_name' => 'Sing Buri',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '135',
                'country_id' => 4,
                'state_name' => 'Chiang Mai',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '136',
                'country_id' => 4,
                'state_name' => 'Nakhon Sawan',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '137',
                'country_id' => 4,
                'state_name' => 'Yala',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '138',
                'country_id' => 4,
                'state_name' => 'Phra Nakhon Si Ayutthaya',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '139',
                'country_id' => 4,
                'state_name' => 'Nonthaburi',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '140',
                'country_id' => 4,
                'state_name' => 'Trat',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '141',
                'country_id' => 4,
                'state_name' => 'Nakhon Ratchasima',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '142',
                'country_id' => 4,
                'state_name' => 'Chiang Rai',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '143',
                'country_id' => 4,
                'state_name' => 'Ratchaburi',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '144',
                'country_id' => 4,
                'state_name' => 'Pathum Thani',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '145',
                'country_id' => 4,
                'state_name' => 'Sakon Nakhon',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '146',
                'country_id' => 4,
                'state_name' => 'Samut Songkhram',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '147',
                'country_id' => 4,
                'state_name' => 'Nakhon Pathom',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '148',
                'country_id' => 4,
                'state_name' => 'Samut Sakhon',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '149',
                'country_id' => 4,
                'state_name' => 'Mae Hong Son',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '150',
                'country_id' => 4,
                'state_name' => 'Phitsanulok',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '151',
                'country_id' => 4,
                'state_name' => 'Pattaya',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '152',
                'country_id' => 4,
                'state_name' => 'Prachuap Khiri Khan',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '153',
                'country_id' => 4,
                'state_name' => 'Loei',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '154',
                'country_id' => 4,
                'state_name' => 'Roi Et',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '155',
                'country_id' => 4,
                'state_name' => 'Kanchanaburi',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '156',
                'country_id' => 4,
                'state_name' => 'Ubon Ratchathani',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '157',
                'country_id' => 4,
                'state_name' => 'Chon Buri',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '158',
                'country_id' => 4,
                'state_name' => 'Phichit',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '159',
                'country_id' => 4,
                'state_name' => 'Phetchabun',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '160',
                'country_id' => 4,
                'state_name' => 'Kamphaeng Phet',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '161',
                'country_id' => 4,
                'state_name' => 'Maha Sarakham',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '162',
                'country_id' => 4,
                'state_name' => 'Rayong',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '163',
                'country_id' => 4,
                'state_name' => 'Ang Thong',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '164',
                'country_id' => 4,
                'state_name' => 'Nakhon Si Thammarat',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '165',
                'country_id' => 4,
                'state_name' => 'Yasothon',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '166',
                'country_id' => 4,
                'state_name' => 'Chai Nat',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '167',
                'country_id' => 4,
                'state_name' => 'Amnat Charoen',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '168',
                'country_id' => 4,
                'state_name' => 'Suphanburi',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '169',
                'country_id' => 4,
                'state_name' => 'Tak',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '170',
                'country_id' => 4,
                'state_name' => 'Chumphon',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '171',
                'country_id' => 4,
                'state_name' => 'Udon Thani',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '172',
                'country_id' => 4,
                'state_name' => 'Phrae',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '173',
                'country_id' => 4,
                'state_name' => 'Sa Kaeo',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '174',
                'country_id' => 4,
                'state_name' => 'Nan',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '175',
                'country_id' => 4,
                'state_name' => 'Surin',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '176',
                'country_id' => 4,
                'state_name' => 'Phetchaburi',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '177',
                'country_id' => 4,
                'state_name' => 'Bueng Kan',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '178',
                'country_id' => 4,
                'state_name' => 'Buri Ram',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '179',
                'country_id' => 4,
                'state_name' => 'Nakhon Nayok',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '180',
                'country_id' => 4,
                'state_name' => 'Phuket',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '181',
                'country_id' => 4,
                'state_name' => 'Satun',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '182',
                'country_id' => 4,
                'state_name' => 'Phayao',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '183',
                'country_id' => 4,
                'state_name' => 'Songkhla',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '184',
                'country_id' => 4,
                'state_name' => 'Pattani',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '185',
                'country_id' => 4,
                'state_name' => 'Trang',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '186',
                'country_id' => 4,
                'state_name' => 'Prachin Buri',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '187',
                'country_id' => 4,
                'state_name' => 'Lopburi',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '188',
                'country_id' => 4,
                'state_name' => 'Lampang',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '189',
                'country_id' => 4,
                'state_name' => 'Sukhothai',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '190',
                'country_id' => 4,
                'state_name' => 'Mukdahan',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '191',
                'country_id' => 4,
                'state_name' => 'Si Sa Ket',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '192',
                'country_id' => 4,
                'state_name' => 'Nakhon Phanom',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '193',
                'country_id' => 4,
                'state_name' => 'Phang Nga',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '194',
                'country_id' => 4,
                'state_name' => 'Kalasin',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '195',
                'country_id' => 4,
                'state_name' => 'Uthai Thani',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '196',
                'country_id' => 4,
                'state_name' => 'Chachoengsao',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '197',
                'country_id' => 4,
                'state_name' => 'Narathiwat',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => '198',
                'country_id' => 4,
                'state_name' => 'Bangkok',
                'state_code' => null,
                'status' => 'active',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ]

//Thailand States Ends here

        ];
        foreach ($states as $state) {
            State::updateOrcreate(['id' => $state['id']], $state);
        }
    }
}
